# -*- coding: utf-8 -*-
"""Linear_Reg_P1Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Et6Y0dPbGjsiB94EQXvrj5Dn9q0g4DLc
"""

import numpy as np
import matplotlib.pyplot as plt

noise = np.random.normal(0,1,10)
x = (np.arange(10)-5)/2
y=np.power(x,3)-np.power(x,2)+1+noise



poly_d1 = np.polyfit(x,y,1)
#print(poly_d1)
poly_d1_val = np.polyval(poly_d1, x)
plt.plot(x,y,'o')
plt.plot(x, poly_d1_val,  'r-')
#plt.show() 

poly_d2 = np.polyfit(x,y,2)
poly_d2_val = np.polyval(poly_d2, x)
plt.plot(x,y,'bo' )
plt.plot(x,poly_d2_val,  'y:')
#plt.show() 

poly_d3 = np.polyfit(x,y,3)
poly_d3_val = np.polyval(poly_d3, x)
plt.plot(x,y,'bo' )
plt.plot(x,poly_d3_val,  'g-')
#plt.show() 

poly_d4 = np.polyfit(x,y,4)
poly_d4_val = np.polyval(poly_d4, x)
plt.plot(x,y,'bo' )
plt.plot(x,poly_d4_val,  'm--')
#plt.show() 

poly_d5 = np.polyfit(x,y,5)
poly_d5_val = np.polyval(poly_d5, x)
plt.plot(x,y,'bo' )
plt.plot(x, poly_d5_val,  'r:')
plt.show()